# Generated by Django 3.1.2 on 2020-10-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='summary',
            field=models.TextField(default='this is a default text for summary'),
        ),
    ]
