# Generated by Django 3.1.2 on 2020-10-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_question_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_next',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='summary',
        ),
    ]
